apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: kubevirt-cluster
spec:
  hosts:
  - ssh:
      address: 3.80.234.62
      user: ubuntu
      port: 22
      keyPath: /Users/kng/Kevin/Work/Mirantis/Demo/certs/kng-msr.pem
    role: controller
  - ssh:
      address: 3.232.131.145
      user: ubuntu
      port: 22
      keyPath: /Users/kng/Kevin/Work/Mirantis/Demo/certs/kng-msr.pem
    role: worker
